apiVersion: batch/v1
kind: Job
metadata:
  name: data-pipeline
spec:
  template:
    metadata:
      name: data-pipeline
    spec:
      restartPolicy: OnFailure
      containers:
      - name: extract
        image: gcr.io/YOUR_PROJECT_ID/data-pipeline-extract:latest
        envFrom:
        - secretRef:
            name: db-credentials
      - name: load
        image: gcr.io/YOUR_PROJECT_ID/data-pipeline-load:latest
        envFrom:
        - secretRef:
            name: db-credentials
      - name: transform
        image: gcr.io/YOUR_PROJECT_ID/data-pipeline-transform:latest
        envFrom:
        - secretRef:
            name: db-credentials