apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP  # Uses ClusterIP instead of LoadBalancer because we don't want to expose the database to the public internet
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432