version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - data-pipeline_mynetwork

networks:
  data-pipeline_mynetwork:
    external: true