apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-pipeline-sequence
spec:
  schedule: "0 0 31 2 *"  # This schedule will effectively never run automatically
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: shared-data
            emptyDir: {}
          initContainers:
          - name: extract
            image: timmanik1/data-pipeline-extract:latest
            envFrom:
            - secretRef:
                name: db-credentials
            volumeMounts:
            - name: shared-data
              mountPath: /data
          - name: load
            image: timmanik1/data-pipeline-load:latest
            envFrom:
            - secretRef:
                name: db-credentials
            volumeMounts:
            - name: shared-data
              mountPath: /data
          containers:
          - name: transform
            image: timmanik1/data-pipeline-transform:latest
            envFrom:
            - secretRef:
                name: db-credentials
            volumeMounts:
            - name: shared-data
              mountPath: /data
