apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: us-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/flask-app:latest
        envFrom:
        - secretRef:
            name: db-credentials
        ports:
        - containerPort: 5000